services:
  db:
    container_name: smart_home_db
    image: postgres:18
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db:/var/lib/postgresql
      - ./src/utils/db/init:/docker-entrypoint-initdb.d

volumes:
  db:
    name: smart_home_db