services:
  app:
    container_name: smart_home_app
    image: smart_home:latest
    build:
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}
        BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
        BETTER_AUTH_URL: ${BETTER_AUTH_URL}
        DOMAIN: ${DOMAIN}
    env_file: ".env"
    ports:
      - ${PORT}:${PORT}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped


  db:
    container_name: smart_home_db
    image: postgres:18
    env_file: ".env"
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db:/var/lib/postgresql
      - ./src/utils/db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  db:
    name: smart_home_db