services:
  app:
    container_name: smart_home_app
    image: smart_home:latest
    build:
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}
        BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
        BETTER_AUTH_URL: ${BETTER_AUTH_URL}
    env_file: ".env"
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped